spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=anime
    username: root
    password: root

## Esconde os logs de erros, para pegar os logs basta passar o parãmetro http://localhost:8080/animes/2?trace=true
server:
  error:
    include-stacktrace: on_param